VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITable"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'Interface for Table and DeltaTable classes
'used to make SubTable class shareable

Public Function GetSigTestVs() As String

End Function

Public Function GetBannerRange() As Range

End Function
